# Generated by Django 3.1.1 on 2021-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='deliverDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='deadline',
            field=models.DateTimeField(default='30-03-2021'),
        ),
    ]
