# Generated by Django 3.1.1 on 2021-03-19 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_auto_20210316_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 12, 19, 58, 12565)),
        ),
    ]
