# Generated by Django 3.1.1 on 2021-03-20 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_auto_20210320_1732'),
        ('requisition', '0004_auto_20210319_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='book',
        ),
        migrations.AddField(
            model_name='requisition',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library.item'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 17, 32, 38, 949255)),
        ),
    ]
