# Generated by Django 3.1.1 on 2021-03-23 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_auto_20210322_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 17, 49, 38, 644258)),
        ),
    ]
