# Generated by Django 3.1.1 on 2021-03-24 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_auto_20210323_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 18, 19, 21, 423321)),
        ),
    ]
