# Generated by Django 3.1.1 on 2021-03-25 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0009_auto_20210324_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 3, 8, 974784)),
        ),
    ]
